# Generated by Django 4.2.3 on 2023-11-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
