# Generated by Django 4.2.3 on 2023-11-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_interview_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabcenter',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
